volumes: 
  db:
  images:
  config:
  custom:
  elastica:

services:
  db:
    image: mariadb:11.8
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mediawiki
      - MYSQL_USER=mediawiki
      - MYSQL_PASSWORD=secret
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_INITDB_SKIP_TZINFO=1
    logging:
      options:
        max-size: 50m
    healthcheck:
      interval: 3s
      retries: 5
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s

  semorg:
    build: ./
    ports:
      - "8081:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=mediawiki
      - MYSQL_USER=mediawiki
      - MYSQL_PASSWORD=secret
      - MEDIAWIKI_LANG=de
      - MEDIAWIKI_ADMIN_USERNAME=admin
      - MEDIAWIKI_ADMIN_PASSWORD=secretpassword
      - MEDIAWIKI_NAME=Testwiki
      - MEDIAWIKI_SERVER=http://localhost:8081
      - MEDIAWIKI_CUSTOM=false
      - MEDIAWIKI_DEBUG=true
      - MEDIAWIKI_ELASTIC=true
      - LANG=de_DE.utf-8
    volumes:
      - images:/var/www/html/images
      - config:/var/www/html/config
      - custom:/var/www/html/extensions/SemanticOrganization/resources/custom
      - .htaccess:/var/www/html/.htaccess:ro
      - ./dumps:/dumps
    depends_on:
      db:
        condition: service_healthy
      elastic:
        condition: service_started
    logging:
      options:
        max-size: 50m

  elastic:
    image: elasticsearch:7.17.21
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elastica:/usr/share/elasticsearch/data
    ports:
      - 9200:9200