version: '3.5'

volumes: 
  db:
  images:
  config:
  custom:
  dumps:

services:
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mediawiki
      - MYSQL_USER=mediawiki
      - MYSQL_PASSWORD=secret  
    logging:
      options:
        max-size: 50m

  web:
    build: ./
    ports:
      - "8081:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=mediawiki
      - MYSQL_USER=mediawiki
      - MYSQL_PASSWORD=secret
      - MEDIAWIKI_LANG=en
      - MEDIAWIKI_ADMIN_USERNAME=admin
      - MEDIAWIKI_ADMIN_PASSWORD=secretpassword
      - MEDIAWIKI_NAME=Testwiki
      - MEDIAWIKI_SERVER=http://localhost:8081
      - MEDIAWIKI_CUSTOM=true
    volumes:
      - images:/var/www/html/images
      - config:/var/www/html/config
      - custom:/var/www/html/extensions/SemanticOrganization/resources/custom
      - .htaccess:/var/www/html/.htaccess:ro
      - ./dumps:/dumps
    depends_on:
      - db
    logging:
      options:
        max-size: 50m
